### ISSUE TITLE
Mapper?

### ISSUE THREAD

**Issue by Jez-net** [unraid/docs#102]
https://github.com/unraid/docs/blame/f20161392486cf69f96f32a0468ed8ff542e4e88/docs/unraid-os/manual/storage-management.md#L1509

To delete the device i had to admit mapper.  

btrfs dev del /dev/mapper/sdX1 /mnt/cache 
btrfs dev del /dev/sdX1 /mnt/cache

when deleting nvme storage the drive leter is not fully shown in the main tab you need to look at the log to see the fully drive.
MAIN: (nvme2n1)
LOG: path /dev/nvme2n1p1

**Comment by ljm42** [comment]
Apologies for not seeing this earlier.

Thanks for calling this out, we have updated the docs to better explain this situation.
