### ISSUE TITLE
Symlinks or Bind Mounts. 

### ISSUE THREAD

**Issue by vyressi** [unraid/docs#108]
https://github.com/unraid/docs/blob/main/docs/unraid-os/release-notes/6.12.0.md as well as the in-app UI indicates that exclusive shares are symlinks

https://unraid.net/blog/6-12-0-stable and screenshots within indicate that exclusive shares are bind mounts.

I believe they are going to be bind mounts, as I don't see how symlinks are going to bypass fuse.

I do not have a ZFS pool in prod to test which is accurate, so I'm not the right person to change this if it needs changed.

**Comment by ljm42** [comment]
Apologies for not seeing this earlier.

Near the end of the 6.12.0 beta cycle we switched from bind mounts (which caused problems) to symlinks for exclusive shares.  Looks like we updated the release notes but missed the blog post, we'll get that fixed.
