### ISSUE TITLE
sh: 1: mcopy: not found

### ISSUE THREAD

**Issue by renjithis** [unraid/docs#186]
KUbuntu 22.04
Need to have mtools package installed when running the script 'make_bootable_linux'. Please add checks for all commands in the script before making changes and exit if any check fails with appropriate message
Since the instructions specify bash, this can be done using
```
if ! hash mcopy; then
  echo "mcopy not found. Please install mtools and run this script again" >&2
  exit 1
fi
```
OR
`hash mcopy || { echo >&2 "mcopy not found. Please install mtools and run this script again"; exit 1; }`

**Comment by ljm42** [comment]
Sounds like a good idea. This is the Unraid Docs repo though so I'll close this and pass the info on to the OS team.
