### ISSUE TITLE
Broken Links in Docs

### ISSUE THREAD

**Issue by elibosley** [unraid/docs#26]
- On source page path = /es/connect/help:
   -> linking to My_Servers#How_to_disable_SSL_for_local_access (resolved as: /es/connect/My_Servers)

- On source page path = /es/connect/remote-access:
   -> linking to Connect#Connect (resolved as: /es/connect/Connect)
   -> linking to My_Servers#A_note_regarding_DNS_Rebinding_Protection (resolved as: /es/connect/My_Servers)
   -> linking to My_Servers#How_to_access_your_server_when_DNS_is_down (resolved as: /es/connect/My_Servers)

- On source page path = /es/legacy/Articles/Expanding_Windows_VM_vdisk_partitions:
   -> linking to Manual/VM_Management#Expanding_a_vdisk (resolved as: /es/legacy/Articles/Manual/VM_Management)

- On source page path = /es/legacy/FAQ/Building_an_unRAID_Server:
   -> linking to Hardware_Compatibility (resolved as: /es/legacy/FAQ/Hardware_Compatibility)
   -> linking to Designing_an_unRAID_server (resolved as: /es/legacy/FAQ/Designing_an_unRAID_server)
   -> linking to UnRAID_Topical_Index#Fans (resolved as: /es/legacy/FAQ/UnRAID_Topical_Index)
   -> linking to FAQ#Apple_Mac_Questions (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to UnRAID_Add_Ons#Preclear_Disk (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)
   -> linking to Telnet (resolved as: /es/legacy/FAQ/Telnet)
   -> linking to Telnet#PuTTY (resolved as: /es/legacy/FAQ/Telnet)
   -> linking to FAQ#unRAID_Console_and_Addon_Questions (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to FAQ (resolved as: /es/legacy/FAQ/FAQ)

- On source page path = /es/legacy/FAQ/Cache_disk:
   -> linking to Plugin/webGui/Cache_Settings (resolved as: /es/legacy/FAQ/Plugin/webGui/Cache_Settings)
   -> linking to Plugin/webGui/Mover_Settings (resolved as: /es/legacy/FAQ/Plugin/webGui/Mover_Settings)
   -> linking to Installing_unRAID_on_a_full_Slackware_distro (resolved as: /es/legacy/FAQ/Installing_unRAID_on_a_full_Slackware_distro)

- On source page path = /es/legacy/FAQ/Configuration_Tutorial:
   -> linking to Upgrading_to_UnRAID_v6 (resolved as: /es/legacy/FAQ/Upgrading_to_UnRAID_v6)
   -> linking to UnRAID_Add_Ons#UnMENU (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)
   -> linking to Troubleshooting#Name_Resolution (resolved as: /es/legacy/FAQ/Troubleshooting)
   -> linking to Telnet (resolved as: /es/legacy/FAQ/Telnet)
   -> linking to Add_One_or_More_New_Data_Drives (resolved as: /es/legacy/FAQ/Add_One_or_More_New_Data_Drives)
   -> linking to User_Benchmarks#Preclear_Times (resolved as: /es/legacy/FAQ/User_Benchmarks)
   -> linking to Un-Official_UnRAID_Manual#Connecting_To_the_Server_Management_Utility (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Shares (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to FAQ#How_do_I_configure_NFS_mounts.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to Un-Official_UnRAID_Manual#Allocation_method (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Split_level (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Included_disk.28s.29 (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Excluded_disks.28s.29 (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Users_2 (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual#Exceptions (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to UnRAID_Manual (resolved as: /es/legacy/FAQ/UnRAID_Manual)
   -> linking to Un-Official_UnRAID_Manual (resolved as: /es/legacy/FAQ/Un-Official_UnRAID_Manual)
   -> linking to UnRAID_Wiki (resolved as: /es/legacy/FAQ/UnRAID_Wiki)
   -> linking to Best_of_the_Forums (resolved as: /es/legacy/FAQ/Best_of_the_Forums)
   -> linking to Troubleshooting (resolved as: /es/legacy/FAQ/Troubleshooting)
   -> linking to UnRAID_Add_Ons (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)

- On source page path = /es/legacy/FAQ/Console:
   -> linking to FAQ#unRAID_Console_Questions (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to FAQ (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to UnRAID_Add_Ons#UnMENU (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)
   -> linking to UnRAID_Topical_Index#SMART (resolved as: /es/legacy/FAQ/UnRAID_Topical_Index)
   -> linking to Troubleshooting#Hard_drive_failures (resolved as: /es/legacy/FAQ/Troubleshooting)

- On source page path = /es/legacy/FAQ/Replacing_a_Data_Drive:
   -> linking to Manual/Storage_Management#Rebuilding_a_drive_onto_itself (resolved as: /es/legacy/FAQ/Manual/Storage_Management)

- On source page path = /es/legacy/FAQ/Replacing_Multiple_Data_Drives_with_a_Single_Larger_Drive:
   -> linking to telnet (resolved as: /es/legacy/FAQ/telnet)
   -> linking to UnRAID_Add_Ons#UnMENU (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)

- On source page path = /es/legacy/FAQ/Terminal_Access:
   -> linking to FAQ#How_is_a_Linux_console_different_from_a_Windows_console.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to FAQ#What_commands_can_I_use_at_the_unRAID_console.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to Introduction_to_the_linux_shell (resolved as: /es/legacy/FAQ/Introduction_to_the_linux_shell)

- On source page path = /es/legacy/FAQ/The_parity_swap_procedure:
   -> linking to Upgrading_to_UnRAID_v6 (resolved as: /es/legacy/FAQ/Upgrading_to_UnRAID_v6)

- On source page path = /es/legacy/FAQ/Transferring_Files_Within_the_unRAID_Server:
   -> linking to Telnet (resolved as: /es/legacy/FAQ/Telnet)
   -> linking to Telnet#PuTTY (resolved as: /es/legacy/FAQ/Telnet)

- On source page path = /es/legacy/FAQ/Understanding_SMART_Reports:
   -> linking to FAQ#How_can_I_find_out_more_information_about_a_hard_drive.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to FAQ#Why_is_a_temp_not_showing_for_a_drive.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to Troubleshooting#Hard_drive_failures (resolved as: /es/legacy/FAQ/Troubleshooting)
   -> linking to UnRAID_Add_Ons#UnMENU (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)
   -> linking to UnRAID_Add_Ons#SmartHistory (resolved as: /es/legacy/FAQ/UnRAID_Add_Ons)

- On source page path = /es/legacy/FAQ/USB_Flash_Drive_Preparation:
   -> linking to Hardware_Compatibility (resolved as: /es/legacy/FAQ/Hardware_Compatibility)
   -> linking to Hardware_Compatibility#USB_Flash_Drives (resolved as: /es/legacy/FAQ/Hardware_Compatibility)
   -> linking to Pre-3.0_Upgrade_Instructions (resolved as: /es/legacy/FAQ/Pre-3.0_Upgrade_Instructions)
   -> linking to FAQ#Flash_Drives (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to FAQ#How_do_I_configure_the_BIOS_settings_to_allow_booting_from_the_USB_flash_drive.3F (resolved as: /es/legacy/FAQ/FAQ)
   -> linking to Best_of_the_Forums#USB_Boot_Issues (resolved as: /es/legacy/FAQ/Best_of_the_Forums)
   -> linking to UnRAID_Topical_Index#PLoP_Boot_Manager (resolved as: /es/legacy/FAQ/UnRAID_Topical_Index)
   -> linking to UnRAID_Topical_Index#Kicker_disks (resolved as: /es/legacy/FAQ/UnRAID_Topical_Index)

- On source page path = /es/unraid-os/faq/licensing-faq:
   -> linking to My_Servers#Navigating_the_User_Profile_Component (resolved as: /es/unraid-os/faq/My_Servers)
   -> linking to './redeem-license-activation-code.md' (resolved as: /es/unraid-os/faq/'./redeem-license-activation-code.md')
   -> linking to Manual/Release_Notes/Unraid_OS_6.9.0#Multiple%20Pools (resolved as: /es/unraid-os/faq/Manual/Release_Notes/Unraid_OS_6.9.0)
   -> linking to Manual/VM_Management (resolved as: /es/unraid-os/faq/Manual/VM_Management)
   -> linking to Manual/Changing_The_Flash_Device (resolved as: /es/unraid-os/faq/Manual/Changing_The_Flash_Device)
   -> linking to Unraid.net/download (resolved as: /es/unraid-os/faq/Unraid.net/download)
   -> linking to Articles/Frequently_Asked_Questions#How_do_I_purchase_Unraid.3F (resolved as: /es/unraid-os/faq/Articles/Frequently_Asked_Questions)

- On source page path = /es/unraid-os/faq/os-faq:
   -> linking to Articles/Getting_Started#Connecting_to_the_Unraid_webGui (resolved as: /es/unraid-os/faq/Articles/Getting_Started)

- On source page path = /es/unraid-os/faq/redeem-license-activation-code:
   -> linking to My_Servers#Navigating_the_User_Profile_Component (resolved as: /es/unraid-os/faq/My_Servers)

- On source page path = /es/unraid-os/manual/additional-settings:
   -> linking to Manual/Docker_Management (resolved as: /es/unraid-os/manual/Manual/Docker_Management)
   -> linking to Manual/VM_Management (resolved as: /es/unraid-os/manual/Manual/VM_Management)
   -> linking to Manual/VM_Guest_Support (resolved as: /es/unraid-os/manual/Manual/VM_Guest_Support)
   -> linking to Manual/Security#WireGuard (resolved as: /es/unraid-os/manual/Manual/Security)

- On source page path = /es/unraid-os/manual/changing-the-flash-device:
   -> linking to Articles/Getting_Started#Manual_Install_Method (resolved as: /es/unraid-os/manual/Articles/Getting_Started)
   -> linking to Articles/Getting_Started#Manual_Method_.28Legacy.29 (resolved as: /es/unraid-os/manual/Articles/Getting_Started)

- On source page path = /es/unraid-os/manual/getting-started:
   -> linking to Articles/Getting_Started#Manual_Install_Method (resolved as: /es/unraid-os/manual/Articles/Getting_Started)
   -> linking to Manual/Security (resolved as: /es/unraid-os/manual/Manual/Security)
   -> linking to M%C3%A9thode_Manuelle_-_Fran%C3%A7ais (resolved as: /es/unraid-os/manual/M%C3%A9thode_Manuelle_-_Fran%C3%A7ais)
   -> linking to Manuelle_Methode_-_Deutsch (resolved as: /es/unraid-os/manual/Manuelle_Methode_-_Deutsch)
   -> linking to %E6%89%8B%E5%8A%A8%E6%96%B9%E5%BC%8F (resolved as: /es/unraid-os/manual/%E6%89%8B%E5%8A%A8%E6%96%B9%E5%BC%8F)
   -> linking to Unraid.net/download (resolved as: /es/unraid-os/manual/Unraid.net/download)

- On source page path = /es/unraid-os/manual/security:
   -> linking to /es/connect/remote-access.mdx

- On source page path = /es/unraid-os/manual/storage-management:
   -> linking to Replacing_a_Data_Drive (resolved as: /es/unraid-os/manual/Replacing_a_Data_Drive)
   -> linking to Manual/Security#Data_Encryption (resolved as: /es/unraid-os/manual/Manual/Security)
   -> linking to Manual/Storage_Management (resolved as: /es/unraid-os/manual/Manual/Storage_Management)
   -> linking to Manual/Storage_Management#Changing_a_File_System_type (resolved as: /es/unraid-os/manual/Manual/Storage_Management)

- On source page path = /es/unraid-os/manual/troubleshooting:
   -> linking to Articles/Getting_Started (resolved as: /es/unraid-os/manual/Articles/Getting_Started)
   -> linking to Manual/Storage_Management#Checking_a_File_System (resolved as: /es/unraid-os/manual/Manual/Storage_Management)
   -> linking to Manual/Storage_Management#Replacing_disks (resolved as: /es/unraid-os/manual/Manual/Storage_Management)

- On source page path = /es/unraid-os/manual/vm-management:
   -> linking to Manual/VM_Guest_Support (resolved as: /es/unraid-os/manual/Manual/VM_Guest_Support)
   -> linking to UnRAID_Manual_6#Lime_Technology_Tested_Components (resolved as: /es/unraid-os/manual/UnRAID_Manual_6)
   -> linking to UnRAID_Manual_6#Assigning_Graphics_Devices_to_Virtual_Machines_.28GPU_Pass_Through.29 (resolved as: /es/unraid-os/manual/UnRAID_Manual_6)
   -> linking to Articles/Expanding_Windows_VM_vdisk_partitions (resolved as: /es/unraid-os/manual/Articles/Expanding_Windows_VM_vdisk_partitions)
   -> linking to Manual/VM_Management#Creating_Your_Own_Virtual_Machines (resolved as: /es/unraid-os/manual/Manual/VM_Management)

- On source page path = /es/unraid-os/manual/vm-support:
   -> linking to Manual/VM_Management (resolved as: /es/unraid-os/manual/Manual/VM_Management)

- On source page path = /es/unraid-os/manual/what-is-unraid:
   -> linking to Manual/Storage_Management (resolved as: /es/unraid-os/manual/Manual/Storage_Management)

- On source page path = /es/unraid-os/release-notes/6.10.0:
   -> linking to Manual/Troubleshooting#System%20Diagnostics (resolved as: /es/unraid-os/release-notes/Manual/Troubleshooting)
   -> linking to Manual/Security#Securing%20webGui%20connections%20.28SSL.29 (resolved as: /es/unraid-os/release-notes/Manual/Security)
   -> linking to Manual/VM_Guest_Support#Upgrading%20a%20VM%20to%20Windows%2011 (resolved as: /es/unraid-os/release-notes/Manual/VM_Guest_Support)
   -> linking to Manual/Shares#User%20Shares (resolved as: /es/unraid-os/release-notes/Manual/Shares)

**Comment by ljm42** [comment]
Resolved in https://github.com/unraid/docs/pull/28
